"""Validate contract-migration SQL generation and abort guards without PostgreSQL."""

import importlib.util
from io import StringIO
from pathlib import Path

import pytest
from alembic.migration import MigrationContext
from alembic.operations import Operations


def migration(counts):
    output = StringIO()
    operations = Operations(
        MigrationContext.configure(
            dialect_name="postgresql", opts={"as_sql": True, "output_buffer": output}
        )
    )

    class Connection:
        def scalar(self, statement):
            return next(counts)

    class Adapter:
        def get_bind(self):
            return Connection()

        def __getattr__(self, name):
            return getattr(operations, name)

    path = (
        Path(__file__).resolve().parents[2]
        / "alembic"
        / "versions"
        / "94d8f2c5b013_enforce_tenant_ownership.py"
    )
    spec = importlib.util.spec_from_file_location("tenancy_contract", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    module.op = Adapter()
    return module, output


def test_contract_migration_renders_identity_addition_and_tenant_constraints():
    module, output = migration(iter([0, 0]))
    module.upgrade()
    sql = output.getvalue()
    assert "ALTER COLUMN number ADD GENERATED BY DEFAULT AS IDENTITY" in sql
    assert "ALTER COLUMN organization_id SET NOT NULL" in sql
    assert "UNIQUE (user_id)" in sql
    assert sql.index("UPDATE restaurants") < sql.index(
        "ALTER COLUMN organization_id SET NOT NULL"
    )
    module.downgrade()
    assert "DROP COLUMN number" in output.getvalue()


@pytest.mark.parametrize(
    "counts,message",
    [([1], "multiple memberships"), ([0, 1], "Backfill every restaurant")],
)
def test_invalid_tenant_backfill_aborts_before_constraints(counts, message):
    module, output = migration(iter(counts))
    with pytest.raises(RuntimeError, match=message):
        module.upgrade()
    assert "ADD COLUMN" not in output.getvalue()
