"""Add menu and menu_items

Revision ID: 694f7189fe51
Revises: 9007636220c5
Create Date: 2026-08-24 16:30:32.098767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '694f7189fe51'
down_revision: Union[str, Sequence[str], None] = '9007636220c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('menu_id')
    )
    op.create_index(op.f('ix_menus_menu_id'), 'menus', ['menu_id'], unique=False)
    op.create_table('menu_items',
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.menu_id'], ),
    sa.PrimaryKeyConstraint('menu_item_id')
    )
    op.create_index(op.f('ix_menu_items_menu_item_id'), 'menu_items', ['menu_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_items_menu_item_id'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_menus_menu_id'), table_name='menus')
    op.drop_table('menus')
    # ### end Alembic commands ###
